apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  labels:
    name: server-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: httpd:2.4-alpine
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
