apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
  namespace: default
  labels:
    app: multi-container-app
spec:
  selector:
    matchLabels:
      app: multi-container-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: nginx-server
          image: nginx:alpine
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: nginx-app
        - name: ubuntu-server
          image: ubuntu:alpine
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: server-app
          command:
            - sleep
            - "3600"

      restartPolicy: Always
